---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/3/6 11:17
---

local LuaItemObject = UnLua.Class()

local new_mt = {__index = function(table, key)
    if table.__item[key] then
        return table.__item[key]
    end
end}

function LuaItemObject:Initialize()
    setmetatable(new_mt, getmetatable(self))
    setmetatable(self, new_mt)
end

return LuaItemObject